// Base64-encoded default profile image (simple avatar icon)
const defaultProfileImage = 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTYgMjU2IiBmaWxsPSIjMDZiNmQzIj48cmVjdCB3aWR0aD0iMjU2IiBoZWlnaHQ9IjI1NiIgZmlsbD0iIzE1MTkyMyIvPjxjaXJjbGUgY3g9IjEyOCIgY3k9IjkwIiByPSI1MCIgZmlsbD0iIzA2YjZkMyIvPjxwYXRoIGQ9Ik0yMzMgMjE2QzIzMyAxOTEgMTk0IDE3MiAxMjggMTcyQzYyIDE3MiAyMyAxOTEgMjMgMjE2QzIzIDI0MSA2MiAyNTYgMTI4IDI1NkMxOTQgMjU2IDIzMyAyNDEgMjMzIDIxNloiIGZpbGw9IiMwNmI2ZDMiLz48L3N2Zz4=';

module.exports = defaultProfileImage; 